<?php
namespace Database\Seeders;

use App\Models\EmailTemplate;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailTemplatesSeeder extends Seeder
{
    public function run()
    {
        // DB::table('email_templates')->truncate();

        $templates = [
            [
                'name' => 'User Mail Send',
                'code' => 'user_mail',
                'for' => 'User',
                'banner' => 'global/images/ZTegliep6F7miE8fiA9e.png',
                'title' => 'User Mail Send',
                'subject' => '[[subject]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => '[[message]]',
                'button_level' => 'Login',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 0,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => 'This is a demo website and demo text.<br />[[site_url]]',
                'short_codes' => '["[[full_name]]","[[site_url]]","[[site_title]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 1,
                'created_at' => '2024-01-17 17:46:20',
                'updated_at' => '2024-01-17 17:46:20',
            ],
            [

                'name' => 'Subscriber Mail Send',
                'code' => 'subscriber_mail',
                'for' => 'Subscriber',
                'banner' => 'global/images/axVxPoEUZq6ge0FDHmtQ.png',
                'title' => 'Welcome to [[site_title]]',
                'subject' => '[[subject]] for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => '[[message]]',
                'button_level' => 'Login',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Thanks for joining our platform!<br />[[site_title]]<br />[[message]]',
                'bottom_status' => 1,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => 'This is a demo website and demo text.<br />[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:50:00',
                'updated_at' => '2024-01-17 17:50:00',
            ],
            [

                'name' => 'Email Verification',
                'code' => 'email_verification',
                'for' => 'User',
                'banner' => 'global/images/eCnEGZZvHeN5Is7dk0VU.jpg',
                'title' => 'Verify Email Address',
                'subject' => 'Verify Email Address',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Hello!<br />Please click the button below to verify your email address.',
                'button_level' => 'Verify Email Address',
                'button_link' => '[[token]]',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Verify Email Address',
                'bottom_body' => 'If you\'re having trouble clicking the "Verify Email Address" button, copy and paste the URL below into your web browser:[[token]]',
                'short_codes' => '["[[token]]","[[full_name]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 10:11:49',
                'updated_at' => '2024-03-11 10:11:49',
            ],
            [

                'name' => 'Forget Password',
                'code' => 'user_password_change',
                'for' => 'User',
                'banner' => 'global/images/2KoCLSWN6kmZXGECOAnd.png',
                'title' => 'Password Reset',
                'subject' => 'Password Reset',
                'salutation' => 'Dear Client,',
                'message_body' => 'Please click the button below to Change the Password.',
                'button_level' => 'Reset Password',
                'button_link' => '[[token]]',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => url('/'),
                'short_codes' => '["[[token]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 10:24:05',
                'updated_at' => '2024-03-11 10:24:05',
            ],
            [
                'name' => 'User Account Disabled',
                'code' => 'user_account_disabled',
                'for' => 'User',
                'banner' => 'global/images/jdmST0fzcBgSUiNZTO4p.png',
                'title' => 'Account Archived',
                'subject' => 'Account Archived',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your account with '.setting('site_title', 'global').' has been successfully archived. You will no longer have access to trading services and features.',
                'button_level' => 'Contact Us',
                'button_link' => 'https://wa.me/message/H5UZC7FCDSSOD1',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'User Account Disabled',
                'bottom_body' => '',
                'short_codes' => '["[[full_name]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:27:01',
                'updated_at' => '2024-03-07 16:27:01',
            ],
            
            [
                'name' => 'Admin Forget Password',
                'code' => 'admin_forget_password',
                'for' => 'Admin',
                'banner' => 'global/images/ZH8Dw583JGGOFKg3x85z.png',
                'title' => 'Admin Forget Password',
                'subject' => 'Admin Forget Password',
                'salutation' => 'Hi Admin,',
                'message_body' => 'Please click the button below to reset your password.',
                'button_level' => 'Password Reset',
                'button_link' => '[[token]]',
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 0,
                'bottom_title' => 'Withdraw Request',
                'bottom_body' => '[[full_name]]<br />[[token]]',
                'short_codes' => '["[[token]]","[[site_title]]","[[site_url]]"]',
                'note' => 'note',
                'support_link' => '',
                'warning_content' => 'note',
                'company_info' => 'note',
                'status' => 0,
                'created_at' => '2024-03-07 12:33:47',
                'updated_at' => '2024-03-07 12:33:47',
            ],
            [
                'name' => 'Contact Mail Send',
                'code' => 'contact_mail',
                'for' => 'Admin',
                'banner' => 'global/images/oPQjJxpFBHFgp7OfYwGQ.png',
                'title' => 'Welcome to [[site_title]]',
                'subject' => '[[subject]] for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => '[[message]]',
                'button_level' => 'Login',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Thanks for joining our platform!<br />[[site_title]]<br />[[message]]',
                'bottom_status' => 1,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:50:56',
                'updated_at' => '2024-01-17 17:50:56',
            ],
            [
                'name' => 'KYC Request',
                'code' => 'kyc_request',
                'for' => 'Admin',
                'banner' => 'global/images/0ZsjvNVZRHnqegdDAPdK.png',
                'title' => 'KYC Request',
                'subject' => 'KYC Request',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We have received your KYC. Our team is currently reviewing the documents. [[site_title]]',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-07 15:16:40',
                'updated_at' => '2024-03-07 15:16:40',
            ],
            [
                'name' => 'KYC Approve',
                'code' => 'kyc_approve',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'KYC Approval Confirmation',
                'subject' => 'KYC Approval Confirmation',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your KYC has been successfully approved. Your account is fully verified. [[site_title]]',
                'button_level' => 'Make Deposit',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'Support Ticket',
                'code' => 'user_support_ticket',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Support Ticket Created Successfully',
                'subject' => 'Support Ticket Created Successfully',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We want to confirm that your support ticket has been successfully created. Our team will get back to you in 24-48 hours.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Ticket Status',
                'bottom_body' => '[[status]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'Support Ticket',
                'code' => 'admin_support_ticket',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'Support Ticket',
                'subject' => 'Support Ticket',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Support Ticket:<br />[[title]]<br />[[message]]<br />[[status]]',
                'button_level' => '..',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'Support Ticket',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-03-06 12:06:50',
                'updated_at' => '2024-03-06 12:06:50',
            ],
//             [
//                 'name' => 'Password Send',
//                 'code' => 'user_password_send',
//                 'for' => 'User',
//                 'banner' => 'global/images/0Qp068vpv0awrGafrXQo.png',
//                 'title' => 'Password Reset Successful',
//                 'subject' => 'Password Reset Successful',
//                 'salutation' => 'Dear Client,',
//                 'message_body' => 'Your password has been successfully reset. This is your current password: [[site_password]]',
//                 'button_level' => 'Login To Your Account',
//                 'button_link' => url('/').'/login',
//                 'footer_status' => 0,
//                 'footer_body' => 'Regards,<br />[[site_title]]',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'More About [[site_title]]',
//                 'bottom_body' => '[[site_url]]',
//                 'short_codes' => '["[[site_title]]","[[site_url]]","[[site_password]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-07 16:24:37',
//                 'updated_at' => '2024-03-07 16:24:37',
//             ],
//             [
//                 'name' => 'New User Welcome',
//                 'code' => 'new_user',
//                 'for' => 'User',
//                 'banner' => 'global/images/4Yqx1Li8ifsWDI52kJO4.png',
//                 'title' => 'Welcome to '.setting('site_title', 'global'),
//                 'subject' => 'Welcome Aboard! Start Your Trading Journey with '.setting('site_title', 'global').'',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'Welcome to '.setting('site_title', 'global').'! Thank you for choosing us. Let\'s start your trading journey.',
//                 'button_level' => 'Make My First Deposit',
//                 'button_link' => url('/').'/user/dashboard',
//                 'footer_status' => 0,
//                 'footer_body' => '',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'More About [[site_title]]',
//                 'bottom_body' => '[[site_url]]',
//                 'short_codes' => '["[[full_name]]","[[site_url]]","[[site_title]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-07 16:24:12',
//                 'updated_at' => '2024-03-07 16:24:12',
//             ],
//             [
//                 'name' => 'Withdraw Request Approve Action',
//                 'code' => 'withdraw_request_user_approve',
//                 'for' => 'User',
//                 'banner' => 'global/images/gK489DY3t8puw9nY5COj.png',
//                 'title' => 'Withdrawal Request Approved',
//                 'subject' => 'Withdrawal Request Approved',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'Your recent withdrawal request of [[withdraw_amount]] has been approved. If you notice any discrepancies, please contact us.',
//                 'button_level' => 'Withdraw Request Approve',
//                 'button_link' => '[[site_url]]',
//                 'footer_status' => 0,
//                 'footer_body' => '',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'Withdrawal ID',
//                 'bottom_body' => '[[txn]]',
//                 'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-11 11:02:02',
//                 'updated_at' => '2024-03-07 16:28:05',
//             ],
//             [
//                 'name' => 'Support Ticket Reply',
//                 'code' => 'user_support_ticket_reply',
//                 'for' => 'User',
//                 'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
//                 'title' => 'Support Ticket Reply',
//                 'subject' => 'Support Ticket Reply',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'We want to confirm that your support ticket has been successfully created. Our team is working diligently to address your inquiry.',
//                 'button_level' => 'Review Your Request',
//                 'button_link' => url('/').'/user/dashboard',
//                 'footer_status' => 0,
//                 'footer_body' => 'Regards,<br />[[site_title]]',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'Ticket Status',
//                 'bottom_body' => '[[status]]',
//                 'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 0,
//                 'created_at' => '2024-03-07 15:50:32',
//                 'updated_at' => '2024-03-07 15:50:32',
//             ],
//             [
//                 'name' => 'Support Ticket Reply',
//                 'code' => 'support_ticket_reply',
//                 'for' => 'User',
//                 'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
//                 'title' => 'Support Ticket Reply',
//                 'subject' => 'Support Ticket Reply',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'We are pleased to inform you that your support ticket has been addressed. You can review the ticket details.',
//                 'button_level' => 'Review Your Request',
//                 'button_link' => url('/').'/user/dashboard',
//                 'footer_status' => 0,
//                 'footer_body' => 'Regards,<br />[[site_title]]',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'Ticket Status',
//                 'bottom_body' => '[[status]]',
//                 'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-07 15:50:32',
//                 'updated_at' => '2024-03-07 15:50:32',
//             ],
//             [

//             [
//                 'name' => 'KYC Approval Confirmation',
//                 'code' => 'kyc_approval_confirmation',
//                 'for' => 'User',
//                 'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
//                 'title' => 'KYC Approval Confirmation',
//                 'subject' => 'KYC Approval Confirmation',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'We are pleased to inform you that your KYC documentation has been reviewed and successfully approved. Your account is now fully verified.',
//                 'button_level' => 'Proceed with Trading',
//                 'button_link' => url('/').'/login',
//                 'footer_status' => 0,
//                 'footer_body' => '',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'More About [[site_title]]',
//                 'bottom_body' => '[[site_url]]',
//                 'short_codes' => '["[[full_name]]","[[kyc_type]]","[[site_url]]","[[site_title]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-07 15:54:46',
//                 'updated_at' => '2024-03-07 15:54:46',
//             ],
//             [
//                 'name' => 'KYC Reject',
//                 'code' => 'kyc_reject',
//                 'for' => 'User',
//                 'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
//                 'title' => 'KYC Rejected',
//                 'subject' => 'KYC Rejection Notice',
//                 'salutation' => 'Dear [[full_name]],',
//                 'message_body' => 'We regret to inform you that your KYC documentation has been rejected. Please provide the correct information to proceed with the verification process.',
//                 'button_level' => 'Resubmit Documents',
//                 'button_link' => url('/').'/login',
//                 'footer_status' => 0,
//                 'footer_body' => '',
//                 'bottom_status' => 1,
//                 'bottom_title' => 'Learn More About [[site_title]]',
//                 'bottom_body' => '[[site_url]]',
//                 'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]","[[kyc_type]]"]',
//                 'note' => '',
//                 'support_link' => '',
//                 'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
//                 'company_info' => 'Brokeret Incorporated by Saint Lucia under registration number 2023-00532.',
//                 'status' => 1,
//                 'created_at' => '2024-03-07 15:54:46',
//                 'updated_at' => '2024-03-07 15:54:46',
//             ],
            [
                'name' => 'New Account Details',
                'code' => 'new_account_details',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'New Account Details',
                'subject' => 'New Account Details',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],
                
Thank you for purchasing package. We’re happy to let you know that your order has been successfully processed, and you are now set to start trading with us.

Here are your MT5 account details for accessing the trading platform:

- MT5 Account ID: [[account_login]]
- Password: [[account_password]]
- Server: [[server]]

Best regards, Support.',
                'button_level' => 'Let\'s Start!',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]","[[account_login]]","[[account_password]]", "[[server]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'Phase Promotion',
                'code' => 'phase_promotion',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Congratulations on Passing [[phase_step]] Phase',
                'subject' => 'Congratulations on Passing [[phase_step]] Phase',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],
                
Congratulations on successfully passing [[phase_step]] phase 🎊 This is a fantastic achievement and a true testament to your dedication and trading skills.

Your hard work and strategic approach have paid off, and you’re now one step closer to achieving your trading goals. We are proud to have you as part of [[site_title]] community and can’t wait to see what you accomplish next! 

The details of the next phase will be shared shortly.

If you have any questions or need support, our team is always here to help. Feel free to reach out to us anytime.

Trade smart,
[[site_title]]
',
                'button_level' => 'Start Trading',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[phase_step]]" ]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'Phase Violation',
                'code' => 'phase_violation',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => '[[phase_step]] Phase Violation',
                'subject' => '[[phase_step]] Phase Violation',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

We regret to inform you that, unfortunately, you did not meet the requirements to successfully complete the [[phase_step]] phase. The reason for phase violation is [[violation_reason]]. While this may feel like a setback, it’s an opportunity to reflect and grow as a trader.

If you have any questions or need support, our team is always here to help. Feel free to reach out to us anytime.

Trade smart,
[[site_title]]
',
                'button_level' => 'Buy Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[phase_step]]", "[[violation_reason]]" ]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'Payment Pending',
                'code' => 'payment_pending',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Payment Pending ([[transaction_id]])',
                'subject' => 'Payment Pending ([[transaction_id]])',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

Thankyou for buying an account on our platform. We have received your payment request of [[amount]] with Transaction ID#[[transaction_id]]. The payment is in the pending state and is currently in reviewing process. Your account will be active once the payment will be approved.
Thanks for your patience.

Trade smart,
[[site_title]]
',
                'button_level' => 'View Account Status',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[transaction_id]]", "[[amount]]" ]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],

            [
                'name' => 'Contract Pending',
                'code' => 'contract_pending',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Contract Pending for Funded Account (#[[account_login]])',
                'subject' => 'Contract Pending for Funded Account (#[[account_login]])',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

Congratulations on successfully passing [[phase_step]] phase 🎊 This is a fantastic achievement and a true testament to your dedication and trading skills.

Before you can move on to the Funded Account, please make sure to submit the contract. After submitting the contract, you\'ll receive the account details to your funded account.

Trade smart,
[[site_title]]
',
                'button_level' => 'Submit Contract',
                'button_link' => route('user.contracts'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[account_login]]", "[[phase_step]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],

            [
                'name' => 'Contract Signed/Submitted',
                'code' => 'contract_signed',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Contract Submitted for Funded Account (#[[account_login]])',
                'subject' => 'Contract Submitted for Funded Account (#[[account_login]])',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

Thanks for submitting the funded account contract. 

Here are your MT5 account details for accessing the trading platform:

- MT5 Account ID: [[account_login]]
- Password: [[account_password]]
- Server: [[server]]

Trade smart,
[[site_title]]
',
                'button_level' => 'My Accounts',
                'button_link' => route('user.investments.index'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[account_login]]", "[[account_password]]", "[[server]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],

            [
                'name' => 'Contract Expired',
                'code' => 'contract_expired',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Contract Expired for Funded Account (#[[account_login]])',
                'subject' => 'Contract Expired for Funded Account (#[[account_login]])',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

We are reaching out to inform you that your contract submission period has expired. Unfortunately, we are unable to proceed to the next steps without the completed contract.

If you have any questions or need support, our team is always here to help. Feel free to reach out to us anytime.

Trade smart,
[[site_title]]
',
                'button_level' => 'My Accounts',
                'button_link' => route('user.investments.index'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],

            [
                'name' => 'Trial Activation',
                'code' => 'trial_activation',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Trial Account Activation',
                'subject' => 'Trial Account Activation',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

The [[package_name]] trial account is active now. The trial account will be active for [[expiry_days]] days and will expire at [[expiry_date]].

Here are your account details for accessing the trading platform:

- MT5 Account ID: [[account_login]]
- Password: [[account_password]]
- Server: [[server]] 

Trade smart,
[[site_title]]
',
                'button_level' => 'My Accounts',
                'button_link' => route('user.investments.index'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[package_name]]", "[[expiry_days]]", "[[expiry_date]]", "[[account_login]]", "[[account_password]]", "[[server]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            [
                'name' => 'Trial Expired',
                'code' => 'trial_expired',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Trial Account Expired',
                'subject' => 'Trial Account Expired',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

Your [[package_name]] trial account has been expired.

Trade smart,
[[site_title]]
',
                'button_level' => 'My Accounts',
                'button_link' => route('user.investments.index'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]", "[[package_name]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Request',
                'code' => 'withdraw_request',
                'for' => 'User',
                'banner' => 'global/images/IZeWtmv9pASv3P4QOL8P.png',
                'title' => 'Withdraw Request',
                'subject' => 'Withdraw Request #[[transaction_id]]',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Dear [[full_name]],

We have received your withdrawal request. Your request has been successfully received and is currently under review.

Here are the details of your transaction:

- Transaction ID: [[transaction_id]]
- Status: [[status]]
- Withdrawal Amount: [[amount]]
- Withdrawal Method: [[withdrawal_method_name]]
- Processing Time: [[processing_time]]

You will receive a confirmation email when the funds are successfully transferred.

Trade smart,
[[site_title]]
',
                'button_level' => 'My Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]", "[[site_title]]","[[full_name]]", "[[transaction_id]]", "[[status]]", "[[amount]]", "[[withdrawal_method_name]]", "[[processing_time]]" ]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Request',
                'code' => 'withdraw_request_admin',
                'for' => 'Admin',
                'banner' => 'global/images/xAt199HeJOZmril5OD45.png',
                'title' => 'Withdraw Request',
                'subject' => 'Withdraw Request #[[transaction_id]]',
                'salutation' => 'Hi Admin,',
                'message_body' => 'Withdraw Request details:

- User Name: [[full_name]] 
- Transaction ID: [[transaction_id]]
- Status: [[status]]
- Withdrawal Amount: [[amount]]
- Withdrawal Method: [[withdrawal_method_name]]
- Processing Time: [[processing_time]]',
                'button_level' => 'View Pending Withdraws',
                'button_link' => route('admin.withdraw.pending'),
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]", "[[site_title]]","[[full_name]]", "[[transaction_id]]", "[[status]]", "[[amount]]", "[[withdrawal_method_name]]", "[[processing_time]]" ]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Request Reject',
                'code' => 'withdraw_request_reject',
                'for' => 'User',
                'banner' => 'global/images/xAt199HeJOZmril5OD45.png',
                'title' => 'Withdraw Request Rejected',
                'subject' => 'Withdraw Request Rejected #[[transaction_id]]',
                'salutation' => '',
                'message_body' => 'Dear [[full_name]],

We are sorry to inform that your withdraw request of amount [[amount]] with transaction id #[[transaction_id]] has been rejected. The amount has been refunded to your [[wallet_type]] wallet.

[[cause]]

Trade smart,
[[site_title]]',

                'button_level' => 'My Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]", "[[site_title]]","[[full_name]]", "[[amount]]", "[[transaction_id]]", "[[wallet_type]]", "[[cause]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Request Approve',
                'code' => 'withdraw_request_approve',
                'for' => 'User',
                'banner' => 'global/images/xAt199HeJOZmril5OD45.png',
                'title' => 'Withdraw Request Approved',
                'subject' => 'Withdraw Request Approved #[[transaction_id]]',
                'salutation' => '',
                'message_body' => 'Dear [[full_name]],

We are delighted to inform that your withdraw request of amount [[amount]] with transaction id #[[transaction_id]] has been approved.

[[cause]]

Trade smart,
[[site_title]]',

                'button_level' => 'My Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => '',
                'bottom_body' => '',
                'short_codes' => '["[[site_url]]", "[[site_title]]","[[full_name]]", "[[amount]]", "[[transaction_id]]", "[[cause]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],


        ];

        foreach ($templates as $template) {
            if(!EmailTemplate::where('code',$template['code'])->exists()) {
                $template['message_body'] = nl2br($template['message_body']);
                EmailTemplate::insert($template);
            }
        }

    }
}
