<?php
namespace Database\Seeders;

use App\Models\EmailTemplate;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\URL;

class EmailTemplatesSeeder extends Seeder
{
    public function run()
    {
//        DB::table('email_templates')->truncate();
        // Define the email template codes to be deleted
//        $codesToDelete = ['transaction_otp'];

        // Delete the existing templates that match the codes
//        EmailTemplate::whereIn('code', $codesToDelete)->delete();


        $templates = [
            [
                'name' => 'Admin Notification - New Staff Created',
                'code' => 'admin_new_staff_created',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'New Staff Created',
                'subject' => 'New Staff Created',
                'salutation' => 'Hi Admin,',
                'message_body' => 'A new staff account was created from the admin panel.<br><br><strong>Name:</strong> [[full_name]]<br><strong>Email:</strong> [[email]]<br><br><strong>Created By:</strong> [[created_by_name]] ( [[created_by_email]] )',
                'button_level' => 'Open Admin Panel',
                'button_link' => URL::to('/admin'),
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Admin Panel',
                'bottom_body' => 'Review in Staff section.',
                'short_codes' => json_encode(["[[full_name]]","[[email]]","[[created_by_name]]","[[created_by_email]]","[[site_title]]","[[site_url]]"]),
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Admin Notification - New User Registered (Direct)',
                'code' => 'admin_new_user_registered_user',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'New User Registered (Direct)',
                'subject' => 'New User Registered (Direct)',
                'salutation' => 'Hi Admin,',
                'message_body' => 'A new user has registered directly on the site.<br><br><strong>Name:</strong> [[full_name]]<br><strong>Email:</strong> [[email]]',
                'button_level' => 'Open Admin Panel',
                'button_link' => URL::to('/admin'),
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Admin Panel',
                'bottom_body' => 'Review in Users section.',
                'short_codes' => json_encode(["[[full_name]]","[[email]]","[[site_title]]","[[site_url]]"]),
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Admin Notification - New User Created (System)',
                'code' => 'admin_new_user_registered_system',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'New User Created (System)',
                'subject' => 'New User Created (System)',
                'salutation' => 'Hi Admin,',
                'message_body' => 'A new user was created by staff from the admin panel.<br><br><strong>Name:</strong> [[full_name]]<br><strong>Email:</strong> [[email]]<br><br><strong>Created By:</strong> [[created_by_name]] ( [[created_by_email]] )',
                'button_level' => 'Open Admin Panel',
                'button_link' => URL::to('/admin'),
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Admin Panel',
                'bottom_body' => 'Review in Users section.',
                'short_codes' => json_encode(["[[full_name]]","[[email]]","[[created_by_name]]","[[created_by_email]]","[[site_title]]","[[site_url]]"]),
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'User Mail Send',
                'code' => 'user_mail',
                'for' => 'User',
                'banner' => 'global/images/ZTegliep6F7miE8fiA9e.png',
                'title' => 'Sample Email',
                'subject' => '[[subject]] for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Thanks for joining us [[site_title]]<br />[[message]]<br />Find out more at - [[site_url]]',
                'button_level' => 'Login Your Account',
                'button_link' => 'https://hyiorio.tdevs.co/login',
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 0,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => 'This is a demo website and demo text.<br />[[site_url]]',
                'short_codes' => '["[[full_name]]","[[site_url]]","[[site_title]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:46:20',
                'updated_at' => '2024-01-17 17:46:20',
            ],
			[
				'name' => 'Withdraw Account Request',
				'code' => 'withdraw_account_request_user',
				'for' => 'User',
				'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
				'title' => 'Withdraw Account Request Received',
				'subject' => 'Your Withdraw Account Request Received',
				'salutation' => 'Dear [[full_name]],',
				'message_body' => 'We\'ve received your withdraw account request for method [[method_name]] (currency: [[currency]]). Our team will review it shortly.',
				'button_level' => 'Login to Your Account',
				'button_link' => url('/').'/login',
				'footer_status' => 1,
				'footer_body' => 'Best Regards,<br />[[site_title]] Team',
				'bottom_status' => 1,
				'bottom_title' => 'Account Request Submitted',
				'bottom_body' => 'You will be notified once your request is reviewed.',
				'short_codes' => json_encode(["[[full_name]]", "[[method_name]]", "[[currency]]", "[[site_title]]", "[[site_url]]"]),
				'note' => 'This email confirms receipt of your withdraw account request.',
				'support_link' => '[[site_url]]/support',
				'warning_content' => 'Security Notice: Never share your account credentials with anyone.',
				'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
				'status' => 1,
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],
			[
				'name' => 'Withdraw Account Request',
				'code' => 'withdraw_account_request',
				'for' => 'Admin',
				'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
				'title' => 'New Withdraw Account Request',
				'subject' => 'Withdraw Account Request Received',
				'salutation' => 'Hi Admin,',
				'message_body' => 'A user has submitted a new withdraw account request.<br><br><strong>User:</strong> [[full_name]]<br><strong>Method:</strong> [[method_name]]<br><strong>Currency:</strong> [[currency]]',
				'button_level' => 'Review Requests',
				'button_link' => URL::to('/admin'),
				'footer_status' => 1,
				'footer_body' => 'Regards,<br />[[site_title]]',
				'bottom_status' => 1,
				'bottom_title' => 'Admin Panel',
				'bottom_body' => 'Navigate to the Withdraw Accounts section to review.',
				'short_codes' => json_encode(["[[full_name]]", "[[method_name]]", "[[currency]]", "[[site_title]]", "[[site_url]]"]),
				'note' => '',
				'support_link' => '',
				'warning_content' => '',
				'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
				'status' => 1,
				'created_at' => Carbon::now(),
				'updated_at' => Carbon::now(),
			],
            [
                'name' => 'New User Under Staff',
                'code' => 'new_user_under_staff',
                'for' => 'Admin',
                'banner' => 'global/images/staff_notification.png',
                'title' => 'A New User Has Been Assigned Under You',
                'subject' => 'New User Assigned',
                'salutation' => 'Dear [[admin_name]],',
                'message_body' => 'A new user has registered using your referral link and has been assigned under your supervision.<br><br>

            <strong>New User Details:</strong><br>
            <strong>Full Name:</strong> [[child_full_name]]<br>
            <strong>Email:</strong> [[child_email]]<br><br>

            You can manage this user from your dashboard.<br><br>',

                'button_level' => 'View User Details',
                'button_link' => URL::to('/admin'),
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[admin_name]]","[[child_full_name]]","[[child_email]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Important: Please ensure the user complies with company policies.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. All rights reserved.',
                'status' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [

                'name' => 'Subscriber Mail Send',
                'code' => 'subscriber_mail',
                'for' => 'Subscriber',
                'banner' => 'global/images/axVxPoEUZq6ge0FDHmtQ.png',
                'title' => 'Welcome to [[site_title]]',
                'subject' => '[[subject]] for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Thanks for joining our platform!<br />[[message]]<br />Find out more at - [[site_url]]',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Thanks for joining our platform!<br />[[site_title]]<br />[[message]]',
                'bottom_status' => 1,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => 'This is a demo website and demo text.<br />[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:50:00',
                'updated_at' => '2024-01-17 17:50:00',
            ],
            [

                'name' => 'Email Verification',
                'code' => 'email_verification',
                'for' => 'User',
                'banner' => 'global/images/email_verification.jpg',
                'title' => 'Verify Your Email Address',
                'subject' => 'Confirm Your Email Address',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Hello!<br />Your One-Time Password (OTP) for email verification is:<br /><strong>[[code]]</strong><br />Please enter this code on the verification page to confirm your email.',
                'button_level' => 'Verify Now',
                'button_link' => '[[site_url]]/verify-email',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Team',
                'bottom_status' => 1,
                'bottom_title' => 'Email Verification Code',
                'bottom_body' => 'This OTP is valid for 30 minutes. Do not share it with anyone for security reasons.',
                'short_codes' => json_encode(["[[code]]", "[[full_name]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you did not request this, please ignore this email.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Never share your verification code with anyone. [[site_title]] will never ask for your OTP.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [

                'name' => 'Forget Password',
                'code' => 'user_password_change',
                'for' => 'User',
                'banner' => 'global/images/2KoCLSWN6kmZXGECOAnd.png',
                'title' => 'Password Reset',
                'subject' => 'Password Reset',
                'salutation' => 'Dear Client,',
                'message_body' => 'Please click the button below to Change the Password.',
                'button_level' => 'Reset Password',
                'button_link' => '[[token]]',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => url('/'),
                'short_codes' => '["[[full_name]]","[[token]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 10:24:05',
                'updated_at' => '2024-03-11 10:24:05',
            ],
            [


                'name' => 'User Forex Account Creation',
                'code' => 'user_forex_account_creation',
                'for' => 'User',
                'banner' => 'global/images/EsCX4Sg9WJF5lSOImDVQ.png',
                'title' => 'You Created Forex Account [[plan_name]]',
                'subject' => 'Thanks for Creating Forex Account on [[site_title]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Hello!<br />Successfully Created Forex Account<br />[[plan_name]]',
                'button_level' => 'Login Account',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'Successfully Created Forex Account',
                'bottom_body' => '[[login]] Successfully Created Forex Account',
                'short_codes' => '["[[full_name]]","[[plan_name]]","[[login]]","[[password]]","[[server]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => '',
                'status' => 1,
                'created_at' => '2024-03-07 15:28:51',
                'updated_at' => '2024-03-07 15:28:51',
            ],
            [
                'name' => 'User Account Disabled',
                'code' => 'user_account_disabled',
                'for' => 'User',
                'banner' => 'global/images/jdmST0fzcBgSUiNZTO4p.png',
                'title' => 'Account Archived',
                'subject' => 'Account Archived',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your account with '.setting('site_title', 'global').' has been successfully archived. You will no longer have access to trading services and features.',
                'button_level' => 'Contact Us',
                'button_link' => 'https://wa.me/message/H5UZC7FCDSSOD1',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'User Account Disabled',
                'bottom_body' => '',
                'short_codes' => '["[[full_name]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:27:01',
                'updated_at' => '2024-03-07 16:27:01',
            ],
            [
                'name' => 'Manual Deposit Request',
                'code' => 'manual_deposit_request',
                'for' => 'Admin',
                'banner' => 'global/images/G5RPUqoKwWOUMoQYKc7h.png',
                'title' => 'Deposit Request',
                'subject' => 'Deposit Request',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We acknowledge the receipt of your deposit request. Our team is currently processing it, and you will be notified once the transaction is complete.',
                'button_level' => 'Review Your Requests',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[txn]]","[[gateway_name]]","[[deposit_amount]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high risk investments, due to their complexity.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-11 10:00:41',
                'updated_at' => '2024-03-11 10:00:41',
            ],
            [
                'name' => 'Withdraw Request',
                'code' => 'withdraw_request',
                'for' => 'Admin',
                'banner' => 'global/images/xAt199HeJOZmril5OD45.png',
                'title' => 'Withdraw Request',
                'subject' => 'Got a Withdraw Request',
                'salutation' => 'Hi Admin,',
                'message_body' => 'Withdraw Request details:<br />[[txn]]<br />[[method_name]]<br />[[withdraw_amount]]',
                'button_level' => 'Withdraw Request',
                'button_link' => '[[token]]',
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 0,
                'bottom_title' => 'Withdraw Request',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[full_name]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:49:12',
                'updated_at' => '2024-01-17 17:49:12',
            ],
            [
                'name' => 'Admin Forget Password',
                'code' => 'admin_forget_password',
                'for' => 'Admin',
                'banner' => 'global/images/ZH8Dw583JGGOFKg3x85z.png',
                'title' => 'Admin Forget Password',
                'subject' => 'Admin Forget Password',
                'salutation' => 'Hi Admin,',
                'message_body' => 'Please click the button below to reset your password.',
                'button_level' => 'Password Reset',
                'button_link' => '[[token]]',
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 0,
                'bottom_title' => 'Withdraw Request',
                'bottom_body' => '[[full_name]]<br />[[token]]',
                'short_codes' => '["[[token]]","[[site_title]]","[[site_url]]"]',
                'note' => 'note',
                'support_link' => '',
                'warning_content' => 'note',
                'company_info' => 'note',
                'status' => 0,
                'created_at' => '2024-03-07 12:33:47',
                'updated_at' => '2024-03-07 12:33:47',
            ],
            [
                'name' => 'Contact Mail Send',
                'code' => 'contact_mail',
                'for' => 'Admin',
                'banner' => 'global/images/oPQjJxpFBHFgp7OfYwGQ.png',
                'title' => 'Welcome to [[site_title]]',
                'subject' => '[[subject]] for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Thanks for joining our platform!<br />[[message]]<br />[[full_name]]<br />[[email]]',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Thanks for joining our platform!<br />[[site_title]]<br />[[message]]',
                'bottom_status' => 1,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[subject]]","[[message]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-01-17 17:50:56',
                'updated_at' => '2024-01-17 17:50:56',
            ],

            [
                'name' => 'KYC Request Received Level-2',
                'code' => 'kyc_request_level_2',
                'for' => 'User',
                'banner' => 'global/images/0ZsjvNVZRHnqegdDAPdK.png',
                'title' => 'KYC Request Received Level-2',
                'subject' => 'KYC Request Received Level-2',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We have received your KYC. Our team is currently reviewing the documents. [[site_title]]',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
            ],
            [
                'name' => 'KYC Request to admin Level-2',
                'code' => 'admin_kyc_request_level_2',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'KYC Request Receive To Admin Level-2',
                'subject' => 'KYC Request Receive To Admin Level-2',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'New kyc request received from user: [[full_name]] of docuemnt type is [[kyc_type]]',
                'button_level' => '..',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'KYC Request Receive',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 1,
                'created_at' => '2024-03-06 12:06:50',
                'updated_at' => '2024-03-06 12:06:50',
            ],
            [
                'name' => 'KYC Approve Level-2',
                'code' => 'kyc_approve_level_2',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'KYC Approve Level-2',
                'subject' => 'KYC Approve Level-2',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your KYC has been successfully approved. Your account is fully verified. [[site_title]]',
                'button_level' => 'Make Deposit',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type_of_name]]","[[message]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'KYC Reject Level-2',
                'code' => 'kyc_reject_level_2',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'KYC Reject Level-2',
                'subject' => 'KYC Reject Level-2',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your KYC documentation has been reviewed but rejected. Please provide accurate information for successful verification.',
                'button_level' => 'Resubmit Documents',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
              [
                'name' => 'KYC Request Received Level-3',
                'code' => 'kyc_request_level_3',
                'for' => 'User',
                'banner' => 'global/images/0ZsjvNVZRHnqegdDAPdK.png',
                'title' => 'KYC Request Received Level-3',
                'subject' => 'KYC Request Received Level-3',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We have received your KYC. Our team is currently reviewing the documents. [[site_title]]',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
            ],
            [
                'name' => 'KYC Request to admin Level-3',
                'code' => 'admin_kyc_request_level_3',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'KYC Request Receive To Admin Level-3',
                'subject' => 'KYC Request Receive To Admin Level-3',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'New kyc request received from user: [[full_name]] of docuemnt type is [[kyc_type]]',
                'button_level' => '..',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'KYC Request Receive',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-03-06 12:06:50',
                'updated_at' => '2024-03-06 12:06:50',
            ],
            [
                'name' => 'KYC Approve Level-3',
                'code' => 'kyc_approve_level_3',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'KYC Approve Level-3',
                'subject' => 'KYC Approve Level-3',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your KYC has been successfully approved. Your account is fully verified. [[site_title]]',
                'button_level' => 'Make Deposit',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[kyc_type_of_name]]","[[message]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [
                'name' => 'KYC Reject Level-3',
                'code' => 'kyc_reject_level_3',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'KYC Reject Level-3',
                'subject' => 'KYC Reject Level-3',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your KYC documentation has been reviewed but rejected. Please provide accurate information for successful verification.',
                'button_level' => 'Resubmit Documents',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[message]]","[[kyc_type]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],

            [
                'name' => 'Withdraw Request Action',
                'code' => 'withdraw_request_user',
                'for' => 'User',
                'banner' => 'global/images/IZeWtmv9pASv3P4QOL8P.png',
                'title' => 'Withdrawal Request',
                'subject' => 'Withdrawal Request',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We have received your withdrawal request. Please note that it can take up to 24 hours.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Withdraw Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:27:50',
                'updated_at' => '2024-03-07 16:27:50',
            ],
            [
                'name' => 'Manual Deposit Request for User',
                'code' => 'user_manual_deposit_request',
                'for' => 'User',
                'banner' => 'global/images/qgv5rYQgsrzumoXEbxZU.png',
                'title' => 'Deposit Request',
                'subject' => 'Deposit Request',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We acknowledge the receipt of your deposit request.',
                'button_level' => 'Review Your Requests',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Deposit Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[gateway_name]]","[[deposit_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:19:27',
                'updated_at' => '2024-03-07 16:19:27',
            ],
            [
                'name' => 'Support Ticket',
                'code' => 'user_support_ticket',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Support Ticket Created Successfully',
                'subject' => 'Support Ticket Created Successfully',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We want to confirm that your support ticket has been successfully created. Our team will get back to you in 24-48 hours.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Ticket Status',
                'bottom_body' => '[[status]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'Support Ticket',
                'code' => 'admin_support_ticket',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'Support Ticket',
                'subject' => 'Support Ticket',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Support Ticket:<br />[[title]]<br />[[message]]<br />[[status]]',
                'button_level' => '..',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'Support Ticket',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-03-06 12:06:50',
                'updated_at' => '2024-03-06 12:06:50',
            ],
            [
                'name' => 'Ticket Assignment',
                'code' => 'support_ticket_assignment',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'Ticket Assignment',
                'subject' => 'A New Ticket has been Assigned to You',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Support Ticket:<br />[[title]]<br />[[message]]<br />[[status]]',
                'button_level' => 'View Ticket',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 0,
                'bottom_title' => 'Support Ticket',
                'bottom_body' => '[[full_name]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-03-06 12:06:50',
                'updated_at' => '2024-03-06 12:06:50',
            ],
            [
                'name' => 'Password Send',
                'code' => 'user_password_send',
                'for' => 'User',
                'banner' => 'global/images/0Qp068vpv0awrGafrXQo.png',
                'title' => 'Password Reset Successful',
                'subject' => 'Password Reset Successful',
                'salutation' => 'Dear Client,',
                'message_body' => 'Your password has been successfully reset. This is your current password: [[site_password]]',
                'button_level' => 'Login To Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_title]]","[[site_url]]","[[site_password]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:24:37',
                'updated_at' => '2024-03-07 16:24:37',
            ],
            [
                'name' => 'IB Request',
                'code' => 'ib_request',
                'for' => 'Admin',
                'banner' => 'global/images/3asEiASbBgqDvIjgnhwd.jpg',
                'title' => 'Welcome to [[site_title]]',
                'subject' => 'for [[full_name]]',
                'salutation' => 'Hi [[full_name]],',
                'message_body' => 'Thanks for joining our platform!<br />[[full_name]]<br />[[email]]<br />Find out more in - [[site_url]]',
                'button_level' => 'Login Your Account',
                'button_link' => '[[site_url]]',
                'footer_status' => 1,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'What is [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]"]',
                'note' => null,
                'support_link' => null,
                'warning_content' => null,
                'company_info' => null,
                'status' => 0,
                'created_at' => '2024-02-19 12:35:27',
                'updated_at' => '2024-03-06 12:06:35',
            ],
            [
                'name' => 'IB Approve Action',
                'code' => 'ib_action',
                'for' => 'User',
                'banner' => 'global/images/dQYA5J7IsEdns1TTIqJ7.png',
                'title' => 'IB Request Approved',
                'subject' => 'IB Request Approved',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Congratulations [[full_name]]! Your IB request has been approved. A dedicated account manager will contact you soon.',
                'button_level' => 'Click Here To Get Started',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Learn More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-02-19 12:37:37',
                'updated_at' => '2024-03-07 15:53:37',
            ],
            [
                'name' => 'New User Welcome',
                'code' => 'new_user',
                'for' => 'User',
                'banner' => 'global/images/4Yqx1Li8ifsWDI52kJO4.png',
                'title' => 'Welcome to '.setting('site_title', 'global'),
                'subject' => 'Welcome Aboard! Start Your Trading Journey with '.setting('site_title', 'global').'',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Welcome to '.setting('site_title', 'global').'! Thank you for choosing us. Let\'s start your trading journey.',
                'button_level' => 'Make My First Deposit',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[site_url]]","[[site_title]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:24:12',
                'updated_at' => '2024-03-07 16:24:12',
            ],
            [
                'name' => 'New User Under IB',
                'code' => 'new_user_ib',
                'for' => 'User',
                'banner' => 'global/images/dLEPbqGONTCxWUPU0ztB.png',
                'title' => 'New User Under IB',
                'subject' => 'New Registration Confirmation',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Congratulations! A new account has been registered under your IB profile at '.setting('site_title', 'global').'.',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[site_url]]","[[site_title]]","[[child_full_name]]","[[child_email]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:23:05',
                'updated_at' => '2024-03-07 16:23:05',
            ],
            [
                'name' => 'User IB Request',
                'code' => 'user_ib_request',
                'for' => 'User',
                'banner' => 'global/images/51OLwANhHCFKeC6J4dVj.png',
                'title' => 'IB Request',
                'subject' => 'IB Request Submitted',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Thank you for expressing interest in becoming an Introducing Broker (IB) with '.setting('site_title', 'global').'. We are reviewing your request.',
                'button_level' => 'Login To Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-02-19 12:35:27',
                'updated_at' => '2024-03-07 16:27:36',
            ],
            [
                'name' => 'IB Reject Action',
                'code' => 'ib_reject_action',
                'for' => 'User',
                'banner' => 'global/images/hF1mZgJGVe42XLpC55SP.png',
                'title' => 'IB Request Rejected',
                'subject' => 'IB Request Rejected',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We regret to inform you that your Introducing Broker (IB) account request has been rejected.',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Learn More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-02-19 12:37:37',
                'updated_at' => '2024-03-07 15:53:51',
            ],
            [
                'name' => 'IB Disable Action',
                'code' => 'ib_disable_action',
                'for' => 'User',
                'banner' => 'global/images/hF1mZgJGVe42XLpC55SP.png',
                'title' => 'IB Disabled',
                'subject' => 'IB Disabled',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We regret to inform you that your Introducing Broker (IB) account has been disabled.',
                'button_level' => 'Login Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Learn More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-02-19 12:37:37',
                'updated_at' => '2024-03-07 15:53:51',
            ],
            [
                'name' => 'Manual Deposit Approve Action',
                'code' => 'user_manual_deposit_approve',
                'for' => 'User',
                'banner' => 'global/images/ZSZdLzk16aDhIFw88bL3.png',
                'title' => 'Deposit Request Approved',
                'subject' => 'Deposit Request Approved',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We are pleased to inform you that your deposit request has been approved. Your funds of [[deposit_amount]] are now available in your account.',
                'button_level' => 'Check Your Account Balance',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Deposit Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[gateway_name]]","[[deposit_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:57:23',
                'updated_at' => '2024-03-07 15:57:23',
            ],
            [
                'name' => 'Manual Deposit Reject Action',
                'code' => 'user_manual_deposit_reject',
                'for' => 'User',
                'banner' => 'global/images/zXk3g2u8Pm3u3KH4mWnC.png',
                'title' => 'Deposit Request Denied',
                'subject' => 'Deposit Request Denied',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We regret to inform you that your deposit request has been denied. Please review the following possible reasons.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Deposit Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[gateway_name]]","[[deposit_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 16:04:32',
                'updated_at' => '2024-03-07 16:04:32',
            ],
            [
                'name' => 'Withdraw Request Approve Action',
                'code' => 'withdraw_request_user_approve',
                'for' => 'User',
                'banner' => 'global/images/gK489DY3t8puw9nY5COj.png',
                'title' => 'Withdrawal Request Approved',
                'subject' => 'Withdrawal Request Approved',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your recent withdrawal request of [[withdraw_amount]] has been approved. If you notice any discrepancies, please contact us.',
                'button_level' => 'Withdraw Request Approve',
                'button_link' => '[[site_url]]',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Withdrawal ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 11:02:02',
                'updated_at' => '2024-03-07 16:28:05',
            ],
            [
                'name' => 'Withdraw Request Reject Action',
                'code' => 'withdraw_request_user_reject',
                'for' => 'User',
                'banner' => 'global/images/OZ5bjEgcgbJzvtODhb6y.png',
                'title' => 'Withdrawal Request Rejected',
                'subject' => 'Withdrawal Request Rejected',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Unfortunately, your withdrawal request of [[withdraw_amount]] has been denied. Please review the reasons below.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Withdraw Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-12 11:02:08',
                'updated_at' => '2024-03-07 16:28:21',
            ],
            [
                'name' => 'Internal Transfer Sender Success',
                'code' => 'internal_transfer_sender',
                'for' => 'User',
                'banner' => 'global/images/x44ZykfSQ7xjI2i4stzR.png',
                'title' => 'Internal Transfer Successful',
                'subject' => 'Internal Transfer Successful',
                'salutation' => 'Dear [[sender_name]],',
                'message_body' => 'Your internal transfer of [[amount]] from account [[account_from]] to [[account_to]] has been completed.',
                'button_level' => 'Login To Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Internal Transfer Success',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[sender_name]]","[[receiver_name]]","[[txn]]","[[account_from]]","[[account_to]]","[[amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 11:02:02',
                'updated_at' => '2024-03-07 15:54:16',
            ],
            [
                 'name' => 'External Transfer Sender Success',
                'code' => 'external_transfer_sender',
                'for' => 'User',
                'banner' => 'global/images/xJIQP5o7tTsyd98zWPPm.png',
                'title' => 'External Transfer Successful',
                'subject' => 'External Transfer Successful',
                'salutation' => 'Dear [[sender_name]],',
                'message_body' => 'Your external transfer request of [[amount]] from [[account_from]] to [[account_to]] has been processed.',
                'button_level' => 'Review Details',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Internal Transfer Success',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[sender_name]]","[[receiver_name]]","[[txn]]","[[account_from]]","[[account_to]]","[[amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-11 11:02:02',
                'updated_at' => '2024-03-07 15:50:45',
            ],
            [
                'name' => 'Support Ticket Reply',
                'code' => 'user_support_ticket_reply',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Support Ticket Reply',
                'subject' => 'Support Ticket Reply',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We want to confirm that your support ticket has been successfully created. Our team is working diligently to address your inquiry.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Ticket Status',
                'bottom_body' => '[[status]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Pending Leverage',
                'code' => 'user_pending_leverage',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Pending Leverage',
                'subject' => 'User Pending Leverage',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] leverage [[leverage]] request has been created. Support team will update ASAP',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Leverage Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[leverage]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Approved Leverage',
                'code' => 'user_approved_leverage',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Pending Leverage',
                'subject' => 'User Pending Leverage',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] leverage [[leverage]] request has been approved.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Login',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[leverage]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Rejected Leverage',
                'code' => 'user_rejected_leverage',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Rejected Leverage',
                'subject' => 'User Rejected Leverage',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] leverage [[leverage]] request has been Rejected.Kindly contact to support '.setting('support_email','global'),
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Login',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[leverage]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Update Investor Password',
                'code' => 'user_update_investor_password',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Update Investor Password',
                'subject' => 'User Update Investor Password',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] Investor Password has been updated.<br />Password: [[password]]',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Investor Password Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[password]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 0,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Update Master Password',
                'code' => 'user_update_master_password',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Update Master Password',
                'subject' => 'User Update Master Password',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] Master Password has been updated.<br />Password: [[password]]',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Master Password Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[password]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Archive Forex Account',
                'code' => 'user_archive_forex_account',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Archive Forex Account',
                'subject' => 'User Archive Forex Account',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] has been archived on your request.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Master Password Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],

            [
                'name' => 'Support Ticket Reply',
                'code' => 'support_ticket_reply',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Support Ticket Reply',
                'subject' => 'Support Ticket Reply',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We are pleased to inform you that your support ticket has been addressed. You can review the ticket details.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Ticket Status',
                'bottom_body' => '[[status]]',
                'short_codes' => '["[[full_name]]","[[title]]","[[message]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'Withdraw Request Reject Action',
                'code' => 'withdraw_request_user_reject',
                'for' => 'User',
                'banner' => 'global/images/OZ5bjEgcgbJzvtODhb6y.png',
                'title' => 'Withdrawal Request Rejected',
                'subject' => 'Withdrawal Request Rejected',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Unfortunately, your [[withdraw_amount]] withdrawal request has been denied. Please review the reasons below.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Withdraw Request ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[message]]","[[txn]]","[[method_name]]","[[withdraw_amount]]","[[site_title]]","[[site_url]]","[[status]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-12 11:02:08',
                'updated_at' => '2024-03-07 16:28:21',
            ],
            [
                'name' => 'Internal Transfer Success',
                'code' => 'internal_transfer_success',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Internal Transfer Success',
                'subject' => 'Internal Transfer Success',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your internal transfer of [[amount]] from account [[account_from]] has been successfully completed.',
                'button_level' => 'Login to Your Account',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Transaction ID',
                'bottom_body' => '[[txn]]',
                'short_codes' => '["[[full_name]]","[[txn]]","[[account_from]]","[[account_to]]","[[amount]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'Investor Password Update',
                'code' => 'investor_password_update',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'Investor Password Update',
                'subject' => 'Investor Password Update',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] Investor Password has been updated. The new password is [[password]].',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Password Updated',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[password]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Update Investor Password',
                'code' => 'user_update_investor_password',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Update Investor Password',
                'subject' => 'User Update Investor Password',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] Investor Password has been updated.<br />Password: [[password]]',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Investor Password Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[password]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Update Master Password',
                'code' => 'user_update_master_password',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Update Master Password',
                'subject' => 'User Update Master Password',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] Master Password has been updated.<br />Password: [[password]]',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Master Password Update',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[password]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],
            [
                'name' => 'User Archive Forex Account',
                'code' => 'user_archive_forex_account',
                'for' => 'User',
                'banner' => 'global/images/tZtWwMyHRy8JqmAgZNsl.png',
                'title' => 'User Archive Forex Account',
                'subject' => 'User Archive Forex Account',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'Your Forex Account [[login]] has been archived at your request.<br /><br />Thank you for choosing '.setting('site_title', 'global').'.',
                'button_level' => 'Review Your Request',
                'button_link' => url('/').'/user/dashboard',
                'footer_status' => 0,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Account Archived',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[full_name]]","[[login]]","[[site_title]]","[[site_url]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => setting('site_title', 'global').' GLOBAL LIMITED Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:50:32',
                'updated_at' => '2024-03-07 15:50:32',
            ],

            [
                'name' => 'Reset Password By Admin',
                'code' => 'reset_user_password_by_admin',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Reset Password By Admin',
                'subject' => 'Reset Password By Admin',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => 'We wanted to inform you that your account password has been reset by an administrator. Please find your new login credentials below:<br />Email: [[email]]<br />Password: [[password]]',
                'button_level' => 'Login',
                'button_link' => url('/').'/login',
                'footer_status' => 0,
                'footer_body' => '',
                'bottom_status' => 1,
                'bottom_title' => 'Learn More About [[site_title]]',
                'bottom_body' => '[[site_url]]',
                'short_codes' => '["[[site_url]]","[[site_title]]","[[full_name]]","[[email]]","[[password]]"]',
                'note' => '',
                'support_link' => '',
                'warning_content' => 'Trading risk Disclaimer: Trading in CFDs and spread bets are high-risk investments.',
                'company_info' => 'Brokeret Incorporated by Saint Lucia under registration number 2023-00532.',
                'status' => 1,
                'created_at' => '2024-03-07 15:54:46',
                'updated_at' => '2024-03-07 15:54:46',
            ],
            [

                'name' => 'Transaction OTP',
                'code' => 'transaction_otp',
                'for' => 'User',
                'banner' => 'global/images/email_verification.jpg',
                'title' => 'Transaction Verification OTP',
                'subject' => 'Important: Verify Your [[site_title]] Transaction OTP',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => '<p><img src="https://cdn.brokeret.com/crm-assets/email/header.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p> <p>Hello <strong>[[full_name]]</strong>,</p>To complete your transaction securely on <strong>[[site_title]]</strong>, please enter the following One-Time Password (OTP)<div style="background-color: #f4f4f4; padding: 16px; border-radius: 8px; text-align: center; font-size: 24px; font-weight: bold; letter-spacing: 2px; margin: 20px 0;">[[code]]</div><p>Enter this code on the verification page to proceed with your transaction.</p><p>If you did not initiate this transaction, please contact our support team immediately.</p>',
                'button_level' => 'Login',
                'button_link' => url('/').'/login',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Team',
                'bottom_status' => 1,
                'bottom_title' => 'Your OTP',
                'bottom_body' => '<p style="font-size: 14px; color: #555;">This OTP is valid for <strong>[[otp_validity]]</strong> minutes. For your protection, do not share this code with anyone.</p><p><img src="https://cdn.brokeret.com/crm-assets/email/footer.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p>',
                'short_codes' => json_encode(["[[code]]", "[[otp_validity]]", "[[transaction_type]]", "[[full_name]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you did not request this, please ignore this email.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Never share your verification code with anyone. [[site_title]] will never ask for your OTP.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'is_disclaimer' => 1,
                'is_risk_warning' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Admin Two-Factor Authentication',
                'code' => 'admin_2fa_verification',
                'for' => 'Admin',
                'banner' => 'global/images/email_verification.jpg',
                'title' => 'Admin Two-Factor Authentication',
                'subject' => 'Two-Factor Authentication Code for [[site_title]] Admin Panel',
                'salutation' => 'Dear [[admin_name]],',
                'message_body' => '<p><img src="https://cdn.brokeret.com/crm-assets/email/header.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p> <p>Hello <strong>[[admin_name]]</strong>,</p><p>To complete your login to the <strong>[[site_title]]</strong> admin panel, please enter the following verification code:</p><div style="background-color: #f4f4f4; padding: 16px; border-radius: 8px; text-align: center; font-size: 24px; font-weight: bold; letter-spacing: 2px; margin: 20px 0;">[[verification_code]]</div><p>Enter this code on the verification page to access your admin dashboard.</p><p>If you did not attempt to log in, please contact our support team immediately.</p>',
                // 'button_level' => 'Access Admin Panel',
                // 'button_link' => url('/').'2fa/verify',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Security Team',
                'bottom_status' => 1,
                'bottom_title' => 'Security Notice',
                'bottom_body' => '<p style="font-color: #555;">This verification code is valid for <strong>[[otp_validity]]</strong> minutes. For your protection, do not share this code with anyone.</p><p><img src="https://cdn.brokeret.com/crm-assets/email/footer.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p>',
                'short_codes' => json_encode(["[[verification_code]]", "[[otp_validity]]", "[[admin_name]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you did not attempt to log in, please ignore this email and contact support immediately.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Never share your verification code with anyone. [[site_title]] will never ask for your verification code.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'is_disclaimer' => 1,
                'is_risk_warning' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'User Withdraw Account Creation OTP',
                'code' => 'user_withdraw_account_otp',
                'for' => 'User',
                'banner' => 'global/images/email_verification.jpg',
                'title' => 'Withdraw Account Creation Verification',
                'subject' => 'Verify Your [[site_title]] Withdraw Account Creation',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => '<p><img src="https://cdn.brokeret.com/crm-assets/email/header.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p> <p>Hello <strong>[[full_name]]</strong>,</p><p>To complete your withdraw account creation securely on <strong>[[site_title]]</strong>, please enter the following verification code:</p><div style="background-color: #f4f4f4; padding: 16px; border-radius: 8px; text-align: center; font-size: 24px; font-weight: bold; letter-spacing: 2px; margin: 20px 0;">[[verification_code]]</div><p>Enter this code on the verification page to complete your withdraw account creation.</p><p>If you did not request this, please contact our support team immediately.</p>',
                'button_level' => 'Complete Account Creation',
                'button_link' => '[[site_url]]/user/settings/withdraw/account',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Security Team',
                'bottom_status' => 1,
                'bottom_title' => 'Security Notice',
                'bottom_body' => '<p style="font-size: 14px; color: #555;">This verification code is valid for <strong>[[otp_validity]]</strong> minutes. For your protection, do not share this code with anyone.</p><p><img src="https://cdn.brokeret.com/crm-assets/email/footer.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p>',
                'short_codes' => json_encode(["[[verification_code]]", "[[otp_validity]]", "[[full_name]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you did not request this, please ignore this email and contact support immediately.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Never share your verification code with anyone. [[site_title]] will never ask for your verification code.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'is_disclaimer' => 1,
                'is_risk_warning' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Account Approval',
                'code' => 'withdraw_account_approval',
                'for' => 'User',
                'banner' => 'global/images/9Eg9j0b3aF4KhRRUL92Q.png',
                'title' => 'Withdraw Account Approved',
                'subject' => 'Your [[site_title]] Withdraw Account Has Been Approved',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => '<p><img src="https://cdn.brokeret.com/crm-assets/email/header.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p> <p>Hello <strong>[[full_name]]</strong>,</p><p>Great news! Your withdraw account has been successfully approved by our team.</p><div style="background-color: #f8f9fa; padding: 16px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #28a745;"><strong>Account Details:</strong><br>Method: [[method_name]]<br>Currency: [[currency]]<br>Status: Approved</div><p>You can now use this account for withdrawals. Please log in to your account to start making withdrawals.</p>',
                'button_level' => 'Login to Your Account',
                'button_link' => '[[site_url]]/login',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Team',
                'bottom_status' => 1,
                'bottom_title' => 'Account Information',
                'bottom_body' => '<p style="font-size: 14px; color: #555;">Your withdraw account is now active and ready for use. If you have any questions, please contact our support team.</p><p><img src="https://cdn.brokeret.com/crm-assets/email/footer.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p>',
                'short_codes' => json_encode(["[[full_name]]", "[[method_name]]", "[[currency]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you did not request this withdraw account, please contact our support team immediately.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Keep your account credentials secure and never share them with anyone.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'is_disclaimer' => 1,
                'is_risk_warning' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Account Approval',
                'code' => 'withdraw_account_approval_admin',
                'for' => 'Admin',
                'banner' => 'global/images/J07DKwijydELjDBznNK4.jpg',
                'title' => 'Withdraw Account Approved',
                'subject' => 'Withdraw Account Approved',
                'salutation' => 'Hi Admin,',
                'message_body' => 'A user\'s withdraw account request has been approved.<br><br><strong>User:</strong> [[full_name]]<br><strong>Method:</strong> [[method_name]]<br><strong>Currency:</strong> [[currency]]',
                'button_level' => 'Go to Admin Panel',
                'button_link' => URL::to('/admin'),
                'footer_status' => 1,
                'footer_body' => 'Regards,<br />[[site_title]]',
                'bottom_status' => 1,
                'bottom_title' => 'Admin Panel',
                'bottom_body' => 'Review this account in Withdraw Accounts section.',
                'short_codes' => json_encode(["[[full_name]]", "[[method_name]]", "[[currency]]", "[[site_title]]", "[[site_url]]"]),
                'note' => '',
                'support_link' => '',
                'warning_content' => '',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Withdraw Account Rejection',
                'code' => 'withdraw_account_rejection',
                'for' => 'User',
                'banner' => 'global/images/hF1mZgJGVe42XLpC55SP.png',
                'title' => 'Withdraw Account Rejected',
                'subject' => 'Your [[site_title]] Withdraw Account Has Been Rejected',
                'salutation' => 'Dear [[full_name]],',
                'message_body' => '<p><img src="https://cdn.brokeret.com/crm-assets/email/header.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p> <p>Hello <strong>[[full_name]]</strong>,</p><p>We regret to inform you that your withdraw account request has been rejected after review.</p><div style="background-color: #f8f9fa; padding: 16px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #dc3545;"><strong>Account Details:</strong><br>Method: [[method_name]]<br>Currency: [[currency]]<br>Status: Rejected</div><p>Please review your account information and resubmit with correct details. If you have any questions, please contact our support team.</p>',
                'button_level' => 'Contact Support',
                'button_link' => '[[site_url]]/support',
                'footer_status' => 1,
                'footer_body' => 'Best Regards,<br />[[site_title]] Team',
                'bottom_status' => 1,
                'bottom_title' => 'Next Steps',
                'bottom_body' => '<p style="font-size: 14px; color: #555;">You can submit a new withdraw account request with corrected information. Our support team is here to help.</p><p><img src="https://cdn.brokeret.com/crm-assets/email/footer.png" style="width: 100%; height: auto;" alt="[[site_title]]"></p>',
                'short_codes' => json_encode(["[[full_name]]", "[[method_name]]", "[[currency]]", "[[rejection_reason]]", "[[site_title]]", "[[site_url]]"]),
                'note' => 'If you believe this is an error, please contact our support team for assistance.',
                'support_link' => '[[site_url]]/support',
                'warning_content' => 'Security Notice: Keep your account credentials secure and never share them with anyone.',
                'company_info' => setting('site_title', 'global') . ' GLOBAL LIMITED. Registered under company number 2023-00532.',
                'status' => 1,
                'is_disclaimer' => 1,
                'is_risk_warning' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ];

        foreach ($templates as $template) {
            if(!EmailTemplate::where('code',$template['code'])->exists()) {
                EmailTemplate::insert($template);
            }
        }
    }
}
