<?php

namespace App\Services;

use Carbon\Carbon;
use App\Models\Addon;
use App\Models\Invoice;
use LaravelDaily\Invoices\Invoice as LDInvoice;
use App\Enums\TxnStatus;
use App\Models\Discount;
use App\Models\Transaction;
use App\Models\AccountTypeInvestment;
use LaravelDaily\Invoices\Classes\Buyer;
use LaravelDaily\Invoices\Classes\InvoiceItem;


class InvoiceService
{

	/**
	 * Generates invoice PDF
	 */
	public function invoicePDF($transaction_id)
	{

		$transaction = Transaction::find($transaction_id);
		$user = $transaction->user;
		$account = AccountTypeInvestment::find($transaction->target_id);
		if (!$account) {
			abort(404);
		}
		$account_type = $account->getAccountTypeSnapshotData();



		// Transaction status
		$transaction_status = '';
		if ($transaction->status == TxnStatus::Success) {
			$transaction_status = 'PAID';
		} elseif ($transaction->status == TxnStatus::Pending) {
			$transaction_status = 'PENDING';
		} elseif ($transaction->status == TxnStatus::Failed) {
			$transaction_status = 'REJECTED';
		}

		$customer = new Buyer([
			'name'          => $user->first_name . ' ' . $user->last_name,
			'custom_fields' => [
				'email' => $user->email,
			],
		]);



		$item = new InvoiceItem();


		if ($transaction->invoice) {

			$item->title($account_type['title'])
				->pricePerUnit($transaction->invoice->package_price);

			//  if has invoice data then use data from invoice db

			$coupon_code_data = $transaction->invoice->coupon_code_discount;
			$addon_data = $transaction->invoice->addon;

			// dd($addon_data, $coupon_code_data);

			$invoice = LDInvoice::make()
				->notes('Invoice automatically generated by ' . setting('site_title'))
				->buyer($customer)
				->addItem($item)
				->currencyCode('USD')
				->currencySymbol(setting('currency_symbol'))
				->status($transaction_status)
				->series('')
				->delimiter('')
				->setCustomData([
					'has_addons' => count($addon_data) != 0 && count($addon_data['items']) > 0 ? true : false,
					'has_coupon_code_discount' => count($coupon_code_data) == 0 ? false : true,

					'package_discount' => $transaction->invoice->package_discount,
					'addons' => count($addon_data) != 0 ? $addon_data['items'] : '',
					'coupon_code' => $coupon_code_data,

					'subtotal' => $transaction->invoice->package_price,
					'transaction_id' => $transaction->tnx
				])
				// ->logo( str_replace("public", 'assets', public_path(setting('site_logo','global') )) )
				// ->sequence($transaction->tnx)
				->totalAmount($transaction->invoice->total_amount)
				->date(Carbon::parse($transaction->created_at))
				->template('invoice');
		} else {

			$item->title($account_type['title'])
				->pricePerUnit($transaction->final_amount);

			// if does not have invoice data then use transaction details
			$invoice = LDInvoice::make()
				->notes('Invoice automatically generated by ' . setting('site_title'))
				->buyer($customer)
				->addItem($item)
				->currencyCode('USD')
				->currencySymbol(setting('currency_symbol'))
				->status($transaction_status)
				->series('')
				->delimiter('')
				->setCustomData([
					'has_addons' => false,
					'has_coupon_code_discount' => false,
					'package_discount' => 0,
					'transaction_id' => $transaction->tnx
				])
				// ->logo( str_replace("public", 'assets', public_path(setting('site_logo','global') )) )
				// ->sequence($transaction->tnx)
				->date(Carbon::parse($transaction->created_at))
				->template('invoice');
		}

		return $invoice;
	}

	/**
	 * Create Invoice Entry in DB
	 */
	public function createInvoice($data, $rule, $new_investment, $total_amount)
	{

		$addons = explode(',', $data['addons']);

		$coupon_code_invoice_data = [];
		$addon_invoice_data = [];
		$invoice = new Invoice();
		$invoice->transaction_id = 0;
		$invoice->account_type_investment_id = $new_investment->id;
		$invoice->transaction_id_string = '';
		$invoice->package_price = $rule->amount;
		$invoice->package_discount = $rule->discount;

		if ($data['discount_id']) {
			$coupon_code_invoice_data = $this->processCouponDiscount($data['discount_id'], $rule->amount)['invoice_data'];
		}
		$invoice->coupon_code_discount = $coupon_code_invoice_data;

		if ($data['addons']) {
			$total_addon = 0;
			$addon_invoice_data['items'] = [];
			for ($i = 0; $i < count($addons); $i++) {
				$amount = 0;
				$addon = Addon::find($addons[$i]);
				$amount = $this->processAddons($addons[$i], $rule->amount);
				$total_addon += $amount;

				if ($addon) {
					array_push($addon_invoice_data['items'], [
						'name' => $addon->name,
						'amount_type' => $addon->amount_type,
						'addon_amount' => $addon->amount,
						'amount' => $amount
					]);
				}
			}
			$addon_invoice_data['total_addon_cost'] = $total_addon;
		}

		$invoice->addon = $addon_invoice_data;
		$invoice->total_amount = $total_amount - $rule->discount;
		$invoice->save();
	}

	/**
	 * Process Coupon Code Discount
	 */
	public function processCouponDiscount($discount_id, $amount)
	{

		// Find the discount using the discount ID
		$discount = Discount::find(get_hash($discount_id));

		// invoice data
		$invoice_data = [
			'code' => $discount->code,
			'amount_type' => $discount->type,
		];

		// If the discount exists and is valid
		if ($discount) {

			if ($discount->implementation != 'default') {
				$levelExists = null;
				foreach ($discount->discount_levels ?? [] as $level) {
					$from = (float) $level['amount_from'];
					$to = (float) $level['amount_to'];

					if ($amount >= $from && $amount <= $to) {
						$levelExists = [
							'amount' => $level['amount'],
							'type' => $level['type'],
						];
						break;
					}
				}

				if ($levelExists) {
					if ($levelExists['type'] == 'percentage') {
						$discountAmount = ($levelExists['amount'] * $discount->percentage) / 100;
						$invoice_data['coupon_amount'] = $discount->percentage;
					} else if ($levelExists['type'] == 'fixed') {
						$discountAmount = $levelExists['amount'];
						$invoice_data['coupon_amount'] = $discount->fixed_amount;
					}
				}
			} else {
				if ($discount->type == 'percentage') {
					$discountAmount = ($amount * $discount->percentage) / 100;
					$invoice_data['coupon_amount'] = $discount->percentage;
				} else if ($discount->type == 'fixed') {
					$discountAmount = $discount->fixed_amount;
					$invoice_data['coupon_amount'] = $discount->fixed_amount;
				}
			}

			// Check if the discount type is percentage
			$finalAmount = $amount - $discountAmount;
			$invoice_data['amount'] = $discountAmount;

			// Ensure the final amount doesn't go below zero
			if ($finalAmount < 0) {
				notify()->error('The selected amount is below then minimum amount! kindly contact to support', 'Error');
				return redirect()->back();
			}



			return ['final_amount' => $finalAmount, 'invoice_data' => $invoice_data];
		}
	}

	/**
	 * Process Addons
	 */
	public function processAddons($id, $amount)
	{

		$addon = Addon::find($id);

		if ($addon) {
			if ($addon->amount_type == 'percentage') {
				$addonAmount = ($amount * $addon->amount) / 100;
			} else if ($addon->amount_type == 'fixed') {
				$addonAmount = $addon->amount;
			}

			return $addonAmount;
		}
	}
}
