INSERT INTO `gateways` (`id`, `logo`, `name`, `gateway_code`, `supported_currencies`, `credentials`, `is_withdraw`, `status`, `created_at`, `updated_at`) VALUES
(18, 'global/gateway/binance.svg', 'Binance', 'binance', '[\"BTC\", \"ETH\", \"BNB\", \"XRP\", \"LTC\", \"BCH\", \"ADA\", \"DOT\", \"LINK\",\"XLM\",\"USDT\",\"USDC\",\"DOGE\",\"SOL\",\"UNI\",\"MATIC\",\"ICP\", \"ETC\", \"XMR\", \"THETA\"]', '{\"api_key\":\"nmgmcaz7oaqijdefee8okmoghsrxrnxzctxzkm7nsgqwjhxe2i7hhyncsgihgxiu\",\"api_secret\":\"birh9qjpyyg4jtt9zsok2ozvpaq3cc9gb1wrtn8ojcnfas71ulg9cxm4su6kttbx\"}', 'address', 1, NULL, '2023-08-17 17:42:51'),
(19, 'global/gateway/cashmaal.png', 'Cashmaal', 'cashmaal', '[\"USD\", \"PKR\"]', '{\"web_id\":\"9101\",\"secret_key\":\"\"}', 'to_email', 1, NULL, '2023-08-19 18:47:56'),
(20, 'global/gateway/blockio.png', 'Block.io', 'blockio', '[\"BTC\", \"LTC\",\"DOGE\"]', '{\"pin\":\"169725cdd2800148b029f804f8f681f102c69b3c\",\"api_key\":\"d4a4-399b-8b74-c73f\"}', 'to_address', 1, NULL, '2023-09-02 14:06:34'),
(21, 'global/gateway/blockchain.png', 'Blockchain', 'blockchain', '[\"BTC\"]', '{\"api_key\":\"21\",\"xpub_code\":\"12\"}', '0', 1, NULL, '2023-08-29 04:30:54'),
(22, 'global/gateway/instamojo.png', 'Instamojo', 'instamojo', '[\"INR\"]', '{\"api_key\":\"test_2241633c3bc44a3de84a3b33969\",\"auth_token\":\"test_279f083f7bebefd35217feef22d\",\"salt\":\"19d38908eeff4f58b2ddda2c6d86ca25\"}', '0', 1, NULL, '2023-08-29 04:30:54'),
(23, 'global/gateway/paytm.png', 'Paytm', 'paytm', '[\"AUD\", \"ARS\", \"BDT\", \"BRL\", \"BGN\", \"CAD\", \"CLP\", \"CNY\", \"COP\",\r\n    \"HRK\", \"CZK\", \"DKK\", \"EGP\", \"EUR\", \"GEL\", \"GHS\", \"HKD\", \"HUF\",\r\n    \"INR\", \"IDR\", \"ILS\", \"JPY\", \"KES\", \"MYR\", \"MXN\", \"MAD\", \"NPR\",\r\n    \"NZD\", \"NGN\", \"NOK\", \"PKR\", \"PEN\", \"PHP\", \"PLN\", \"RON\", \"RUB\",\r\n    \"SGD\", \"ZAR\", \"KRW\", \"LKR\", \"SEK\", \"CHF\", \"THB\", \"TRY\", \"UGX\",\r\n    \"UAH\", \"AED\", \"GBP\", \"USD\", \"VND\", \"XOF\"]', '{\"merchant_id\":\"DIY12386817555501617\",\"merchant_key\":\"bKMfNxPPf_QdZppa\",\"merchant_website\":\"DIYtestingweb\",\"channel\":\"WEB\",\"industry_type\":\"Retail\"}', '0', 1, NULL, '2023-08-30 07:47:57'),
(24, 'global/gateway/razorpay.png', 'Razorpay', 'razorpay', '[\"INR\"]', '{\"razorpay_key\":\"rzp_test_kiOtejPbRZU90E\",\"razorpay_secret\":\"osRDebzEqbsE1kbyQJ4y0re7\"}', '0', 1, NULL, '2023-08-30 14:13:27'),
(25, 'global/gateway/twocheckout.png', '2Checkout', 'twocheckout', '[\"AFN\", \"ALL\", \"DZD\", \"ARS\", \"AUD\", \"AZN\", \"BSD\", \"BDT\", \"BBD\", \"BZD\", \r\n    \"BMD\", \"BOB\", \"BWP\", \"BRL\", \"GBP\", \"BND\", \"BGN\", \"CAD\", \"CLP\", \"CNY\", \r\n    \"COP\", \"CRC\", \"HRK\", \"CZK\", \"DKK\", \"DOP\", \"XCD\", \"EGP\", \"EUR\", \"FJD\", \r\n    \"GTQ\", \"HKD\", \"HNL\", \"HUF\", \"INR\", \"IDR\", \"ILS\", \"JMD\", \"JPY\", \"KZT\", \r\n    \"KES\", \"LAK\", \"MMK\", \"LBP\", \"LRD\", \"MOP\", \"MYR\", \"MVR\", \"MRO\", \"MUR\", \r\n    \"MXN\", \"MAD\", \"NPR\", \"TWD\", \"NZD\", \"NIO\", \"NOK\", \"PKR\", \"PGK\", \"PEN\", \r\n    \"PHP\", \"PLN\", \"QAR\", \"RON\", \"RUB\", \"WST\", \"SAR\", \"SCR\", \"SGD\", \"SBD\", \r\n    \"ZAR\", \"KRW\", \"LKR\", \"SEK\", \"CHF\", \"SYP\", \"THB\", \"TOP\", \"TTD\", \"TRY\", \r\n    \"UAH\", \"AED\", \"USD\", \"VUV\", \"VND\", \"XOF\", \"YER\"]', '{\"seller_id\":\"250507228545\",\"secret_word\":\"=+0CNzfvTItqp*ygwiQE\"}', '0', 1, NULL, '2023-08-30 14:13:27');

